# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: chat.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='chat.proto',
  package='chat',
  syntax='proto3',
  serialized_pb=_b('\n\nchat.proto\x12\x04\x63hat\"Q\n\x10msg_chat_request\x12\x0e\n\x06\x64\x65vice\x18\x01 \x01(\x05\x12\x10\n\x08\x66rom_uid\x18\x02 \x01(\x05\x12\x0e\n\x06to_uid\x18\x03 \x01(\x05\x12\x0b\n\x03msg\x18\x04 \x01(\t\"O\n\x0emsg_chat_reply\x12\x10\n\x08\x66rom_uid\x18\x01 \x01(\x05\x12\x0e\n\x06to_uid\x18\x02 \x01(\x05\x12\x0e\n\x06result\x18\x03 \x01(\x05\x12\x0b\n\x03msg\x18\x04 \x01(\t\"#\n\x06Person\x12\x0b\n\x03\x61ge\x18\x01 \x01(\x05\x12\x0c\n\x04name\x18\x02 \x01(\t\"&\n\x06\x46\x61mily\x12\x1c\n\x06person\x18\x01 \x03(\x0b\x32\x0c.chat.Personb\x06proto3')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_MSG_CHAT_REQUEST = _descriptor.Descriptor(
  name='msg_chat_request',
  full_name='chat.msg_chat_request',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='device', full_name='chat.msg_chat_request.device', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='from_uid', full_name='chat.msg_chat_request.from_uid', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='to_uid', full_name='chat.msg_chat_request.to_uid', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='msg', full_name='chat.msg_chat_request.msg', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=20,
  serialized_end=101,
)


_MSG_CHAT_REPLY = _descriptor.Descriptor(
  name='msg_chat_reply',
  full_name='chat.msg_chat_reply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='from_uid', full_name='chat.msg_chat_reply.from_uid', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='to_uid', full_name='chat.msg_chat_reply.to_uid', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='result', full_name='chat.msg_chat_reply.result', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='msg', full_name='chat.msg_chat_reply.msg', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=103,
  serialized_end=182,
)


_PERSON = _descriptor.Descriptor(
  name='Person',
  full_name='chat.Person',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='age', full_name='chat.Person.age', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='name', full_name='chat.Person.name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=184,
  serialized_end=219,
)


_FAMILY = _descriptor.Descriptor(
  name='Family',
  full_name='chat.Family',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='person', full_name='chat.Family.person', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=221,
  serialized_end=259,
)

_FAMILY.fields_by_name['person'].message_type = _PERSON
DESCRIPTOR.message_types_by_name['msg_chat_request'] = _MSG_CHAT_REQUEST
DESCRIPTOR.message_types_by_name['msg_chat_reply'] = _MSG_CHAT_REPLY
DESCRIPTOR.message_types_by_name['Person'] = _PERSON
DESCRIPTOR.message_types_by_name['Family'] = _FAMILY

msg_chat_request = _reflection.GeneratedProtocolMessageType('msg_chat_request', (_message.Message,), dict(
  DESCRIPTOR = _MSG_CHAT_REQUEST,
  __module__ = 'chat_pb2'
  # @@protoc_insertion_point(class_scope:chat.msg_chat_request)
  ))
_sym_db.RegisterMessage(msg_chat_request)

msg_chat_reply = _reflection.GeneratedProtocolMessageType('msg_chat_reply', (_message.Message,), dict(
  DESCRIPTOR = _MSG_CHAT_REPLY,
  __module__ = 'chat_pb2'
  # @@protoc_insertion_point(class_scope:chat.msg_chat_reply)
  ))
_sym_db.RegisterMessage(msg_chat_reply)

Person = _reflection.GeneratedProtocolMessageType('Person', (_message.Message,), dict(
  DESCRIPTOR = _PERSON,
  __module__ = 'chat_pb2'
  # @@protoc_insertion_point(class_scope:chat.Person)
  ))
_sym_db.RegisterMessage(Person)

Family = _reflection.GeneratedProtocolMessageType('Family', (_message.Message,), dict(
  DESCRIPTOR = _FAMILY,
  __module__ = 'chat_pb2'
  # @@protoc_insertion_point(class_scope:chat.Family)
  ))
_sym_db.RegisterMessage(Family)


# @@protoc_insertion_point(module_scope)
