# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: route_database.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='route_database.proto',
  package='route_database',
  syntax='proto3',
  serialized_pb=_b('\n\x14route_database.proto\x12\x0eroute_database\",\n\x05Point\x12\x10\n\x08latitude\x18\x01 \x01(\x05\x12\x11\n\tlongitude\x18\x02 \x01(\x05\"@\n\x07\x46\x65\x61ture\x12\'\n\x08location\x18\x01 \x01(\x0b\x32\x15.route_database.Point\x12\x0c\n\x04name\x18\x02 \x01(\t\"\x1c\n\x0cPointRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\"\x1d\n\nPointReply\x12\x0f\n\x07message\x18\x01 \x01(\t\"9\n\x0e\x46\x65\x61tureRequest\x12\'\n\x08location\x18\x01 \x01(\x0b\x32\x15.route_database.Point\"8\n\x0c\x46\x65\x61tureReply\x12(\n\x07\x66\x65\x61ture\x18\x01 \x01(\x0b\x32\x17.route_database.Feature2\xbc\x02\n\x0cRouteGreeter\x12L\n\nGetFeature\x12\x1e.route_database.FeatureRequest\x1a\x1c.route_database.FeatureReply\"\x00\x12J\n\x0cListFeatures\x12\x1c.route_database.PointRequest\x1a\x1a.route_database.PointReply\"\x00\x12I\n\x0bRecordRoute\x12\x1c.route_database.PointRequest\x1a\x1a.route_database.PointReply\"\x00\x12G\n\tRouteChat\x12\x1c.route_database.PointRequest\x1a\x1a.route_database.PointReply\"\x00\x62\x06proto3')
)




_POINT = _descriptor.Descriptor(
  name='Point',
  full_name='route_database.Point',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='latitude', full_name='route_database.Point.latitude', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='longitude', full_name='route_database.Point.longitude', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=40,
  serialized_end=84,
)


_FEATURE = _descriptor.Descriptor(
  name='Feature',
  full_name='route_database.Feature',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='location', full_name='route_database.Feature.location', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='name', full_name='route_database.Feature.name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=86,
  serialized_end=150,
)


_POINTREQUEST = _descriptor.Descriptor(
  name='PointRequest',
  full_name='route_database.PointRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='route_database.PointRequest.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=152,
  serialized_end=180,
)


_POINTREPLY = _descriptor.Descriptor(
  name='PointReply',
  full_name='route_database.PointReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='message', full_name='route_database.PointReply.message', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=182,
  serialized_end=211,
)


_FEATUREREQUEST = _descriptor.Descriptor(
  name='FeatureRequest',
  full_name='route_database.FeatureRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='location', full_name='route_database.FeatureRequest.location', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=213,
  serialized_end=270,
)


_FEATUREREPLY = _descriptor.Descriptor(
  name='FeatureReply',
  full_name='route_database.FeatureReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='feature', full_name='route_database.FeatureReply.feature', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=272,
  serialized_end=328,
)

_FEATURE.fields_by_name['location'].message_type = _POINT
_FEATUREREQUEST.fields_by_name['location'].message_type = _POINT
_FEATUREREPLY.fields_by_name['feature'].message_type = _FEATURE
DESCRIPTOR.message_types_by_name['Point'] = _POINT
DESCRIPTOR.message_types_by_name['Feature'] = _FEATURE
DESCRIPTOR.message_types_by_name['PointRequest'] = _POINTREQUEST
DESCRIPTOR.message_types_by_name['PointReply'] = _POINTREPLY
DESCRIPTOR.message_types_by_name['FeatureRequest'] = _FEATUREREQUEST
DESCRIPTOR.message_types_by_name['FeatureReply'] = _FEATUREREPLY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Point = _reflection.GeneratedProtocolMessageType('Point', (_message.Message,), dict(
  DESCRIPTOR = _POINT,
  __module__ = 'route_database_pb2'
  # @@protoc_insertion_point(class_scope:route_database.Point)
  ))
_sym_db.RegisterMessage(Point)

Feature = _reflection.GeneratedProtocolMessageType('Feature', (_message.Message,), dict(
  DESCRIPTOR = _FEATURE,
  __module__ = 'route_database_pb2'
  # @@protoc_insertion_point(class_scope:route_database.Feature)
  ))
_sym_db.RegisterMessage(Feature)

PointRequest = _reflection.GeneratedProtocolMessageType('PointRequest', (_message.Message,), dict(
  DESCRIPTOR = _POINTREQUEST,
  __module__ = 'route_database_pb2'
  # @@protoc_insertion_point(class_scope:route_database.PointRequest)
  ))
_sym_db.RegisterMessage(PointRequest)

PointReply = _reflection.GeneratedProtocolMessageType('PointReply', (_message.Message,), dict(
  DESCRIPTOR = _POINTREPLY,
  __module__ = 'route_database_pb2'
  # @@protoc_insertion_point(class_scope:route_database.PointReply)
  ))
_sym_db.RegisterMessage(PointReply)

FeatureRequest = _reflection.GeneratedProtocolMessageType('FeatureRequest', (_message.Message,), dict(
  DESCRIPTOR = _FEATUREREQUEST,
  __module__ = 'route_database_pb2'
  # @@protoc_insertion_point(class_scope:route_database.FeatureRequest)
  ))
_sym_db.RegisterMessage(FeatureRequest)

FeatureReply = _reflection.GeneratedProtocolMessageType('FeatureReply', (_message.Message,), dict(
  DESCRIPTOR = _FEATUREREPLY,
  __module__ = 'route_database_pb2'
  # @@protoc_insertion_point(class_scope:route_database.FeatureReply)
  ))
_sym_db.RegisterMessage(FeatureReply)



_ROUTEGREETER = _descriptor.ServiceDescriptor(
  name='RouteGreeter',
  full_name='route_database.RouteGreeter',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=331,
  serialized_end=647,
  methods=[
  _descriptor.MethodDescriptor(
    name='GetFeature',
    full_name='route_database.RouteGreeter.GetFeature',
    index=0,
    containing_service=None,
    input_type=_FEATUREREQUEST,
    output_type=_FEATUREREPLY,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='ListFeatures',
    full_name='route_database.RouteGreeter.ListFeatures',
    index=1,
    containing_service=None,
    input_type=_POINTREQUEST,
    output_type=_POINTREPLY,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='RecordRoute',
    full_name='route_database.RouteGreeter.RecordRoute',
    index=2,
    containing_service=None,
    input_type=_POINTREQUEST,
    output_type=_POINTREPLY,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='RouteChat',
    full_name='route_database.RouteGreeter.RouteChat',
    index=3,
    containing_service=None,
    input_type=_POINTREQUEST,
    output_type=_POINTREPLY,
    options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_ROUTEGREETER)

DESCRIPTOR.services_by_name['RouteGreeter'] = _ROUTEGREETER

# @@protoc_insertion_point(module_scope)
